apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: basicapp-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: basicapp
    spec:
      containers:
      - name: docker-demo-101
        image: jragan/docker-demo-101
        ports:
        - name: nodejs-port
          containerPort: 3000
        volumeMounts:
        - name: cred-volume
          mountPath: /etc/creds
          readOnly: true
        env:
          - name: MONGO_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: username
          - name: MONGO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: password  
      volumes:
      - name: cred-volume
        secret: 
          secretName: db-secrets
          
