apiVersion: apps/v1
kind: Deployment
metadata:
  name: basicapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: basicapp
  template:
    metadata:
      labels:
        app: basicapp
    spec:
      containers:
      - name: docker-demo-101
        image: jragan/docker-demo-101
        ports:
        - name: nodejs-port
          containerPort: 3000
