apiVersion: v1
kind: Service
metadata:
  name: basicapp
  labels:
    app: basicapp
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: NodePort
  selector:
    app: basicapp
    