apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: basicapp-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: docker-demo-101
    spec:
      containers:
      - name: docker-demo-101
        image: jragan/docker-demo-101
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; touch /tmp/ready; sleep 600
        #- touch /tmp/healthy; sleep 45; touch /tmp/ready; sleep 45; rm -rf /tmp/ready; sleep 45; touch /tmp/ready; sleep 600
        #- touch /tmp/healthy; touch /tmp/ready; sleep 50; rm -rf /tmp/healthy; sleep 600
        ports:
        - name: nodejs-port
          containerPort: 3000
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 20
          timeoutSeconds: 20    
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/ready
          initialDelaySeconds: 20
          timeoutSeconds: 20  
